github.com:
    users:
        VitorSantos1YT:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: VitorSantos1YT
